environment:
  game: 'mario'
  level: 'SuperMarioBros-1-1-v0'
  action_space: 'SIMPLE_MOVEMENT'
  skip: 4
  gray_scale: True
  frame_shape:
    - 84
    - 84 
  num_stack: 4

hyperparameters:
  dqn/ddqn:
    model: 'DDQN'
    #batch_size: 32 #TUNED
    batch_size: 192 #TUNED
    buffer_size: 100000 #TUNED
    learning_starts: 10000 #TUNED
    discount_factor: 0.99 #TUNED
    exploration_fraction: 0.1 #TUNED

    learning_rate: 0.0001    
    exploration_final_eps: 0.1
    train_freq: 8
    #train_freq: 4
    target_update_interval: 100000
    #time_steps: 2000000
    time_steps: 4000000
  
  ppo:
    model: 'PPO'
    learning_rate: 0.00003  
    time_steps: 3000000

logging:
  n_time_steps_save_model: 25000
  evaluate_best_model_every: 250000