environment:
  game: 'mario'
  level: 'SuperMarioBros-1-1-v0'
  action_space: 'RIGHT_ONLY'
  skip: 'max_and_skip'
  gray_scale: True
  frame_shape:
    - 84
    - 84
  num_stack: 4
  buffer: True

hyperparameters:
  dqn/ddqn:
    model: 'DDQN'
    batch_size: 32 #TUNED
    buffer_size: 30000 #TUNED
    learning_starts: 1000 #TUNED
    discount_factor: 0.90 #TUNED
    learning_rate: 0.00025
    train_freq: 3
    target_update_interval: 5000
    
    #Own implementation
    num_episodes: 10000
    exploration_decay: 0.99
    exploration_min: 0.02

    # SB
    exploration_fraction: 0.1 #TUNED
    exploration_final_eps: 0.1
    time_steps: 4000000
  
  ppo:
    model: 'PPO'
    learning_rate: 0.00003  
    time_steps: 3000000

logging:
  n_time_steps_save_model: 25000
  evaluate_best_model_every: 250000